apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-ts-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/org-tests-ca/platform-engineering-p01.git
    targetRevision: develop
    path: charts/api-ts
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
