apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-ts-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/org-tests-ca/platform-engineering-p01
    targetRevision: develop
    path: charts/api-ts
    helm:
      valueFiles:
        - environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
